import 'package:flutter/material.dart';
import '../../data/item_data.dart';

class ItemEdit extends StatelessWidget {
  ItemEdit({ Key? key, required this.item, this.onEditFinish, required this.editRole }) : super(key: key);

  final Item item; 
  final String editRole;
  final onEditFinish;
  final itemFormKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    Item newItem = item;
    return editRole == "edit" ? TextButton(
      style: ButtonStyle(padding: MaterialStateProperty.all<EdgeInsets>(EdgeInsets.zero)),
      onPressed: () {
        showFormDialog(context, newItem);
      },
      child: const Text("Edit"),
    ) : FloatingActionButton(
      child: const Icon(Icons.add),
      onPressed: (){
        showFormDialog(context, newItem);
      },
    );
  }

  void showFormDialog(BuildContext context, Item newItem) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          scrollable: true,
          content: Stack(
            clipBehavior: Clip.antiAlias,
            children: <Widget>[
              Positioned(
                right: -40.0,
                top: -40.0,
                child: InkResponse(
                  onTap: () {
                    Navigator.of(context).pop();
                  },
                  child: const CircleAvatar(
                    child: Icon(Icons.close),
                    backgroundColor: Colors.red,
                  ),
                ),
              ),
              Form(
                key: itemFormKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Name',
                        ),
                        initialValue: item.name,
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Name Can't be Empty";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newItem.name = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Type',
                        ),
                        initialValue: item.type,
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Type Can't be Empty";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newItem.type = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'ID',
                          hintText: "Will be generated by system",
                        ),
                        initialValue: item.id,
                        readOnly: true,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Date',
                        ),
                        initialValue: item.date,
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Date Can't be Empty";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newItem.date = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Price',
                        ),
                        initialValue: item.price,
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Price Can't be Empty";
                          } else if (int.parse(value) < 0) {
                            return "The Price Should Large Than 0";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newItem.price = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Image',
                        ),
                        initialValue: item.image,
                        onSaved: (newValue) => newItem.image = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Location',
                        ),
                        initialValue: item.location,
                        onSaved: (newValue) => newItem.location = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: ElevatedButton(
                        child: const Text("Submit"),
                        onPressed: () {
                          if (itemFormKey.currentState!.validate()) {
                            itemFormKey.currentState!.save();
                            onEditFinish(newItem);
                            Navigator.pop(context);
                          }
                        },
                      ),
                    )
                  ],
                ),
              ),
            ],
          ),
        );
      }
    );
  }
}

