import 'package:flutter/material.dart';
import '../../data/product_data.dart';
import 'package:intl/intl.dart';

class ProductEdit extends StatelessWidget {
  ProductEdit({ Key? key, required this.product, this.onEditFinish, required this.editRole }) : super(key: key);

  final Product product; 
  final String editRole;
  final onEditFinish;
  final productFormKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    Product newProduct = product;
    return editRole == "edit" ? Row(
      children: [
        TextButton(
          style: ButtonStyle(padding: MaterialStateProperty.all<EdgeInsets>(EdgeInsets.zero)),
          onPressed: () {
            showFormDialog(context, newProduct, 'update');
          },
          child: const Text("Edit")
        ),
        TextButton(
          style: ButtonStyle(padding: MaterialStateProperty.all<EdgeInsets>(EdgeInsets.zero)),
          onPressed: () {
            onEditFinish(newProduct, 'delete');
          },
          child: const Text("Delete")
        ),
      ]
    ) : FloatingActionButton(
      child: const Icon(Icons.add),
      onPressed: (){
        showFormDialog(context, newProduct, 'add');
      },
    );
  }

  void showFormDialog(BuildContext context, Product newProduct, String type) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          scrollable: true,
          content: Stack(
            clipBehavior: Clip.antiAlias,
            children: <Widget>[
              Positioned(
                right: -40.0,
                top: -40.0,
                child: InkResponse(
                  onTap: () {
                    Navigator.of(context).pop();
                  },
                  child: const CircleAvatar(
                    child: Icon(Icons.close),
                    backgroundColor: Colors.red,
                  ),
                ),
              ),
              Form(
                key: productFormKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Name',
                        ),
                        initialValue: product.name,
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Name Can't be Empty";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newProduct.name = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Category',
                        ),
                        initialValue: product.category,
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Category Can't be Empty";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newProduct.category = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Product_ID',
                          hintText: "Will be generated by system",
                        ),
                        initialValue: "",
                        readOnly: true,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Date',
                        ),
                        initialValue: DateFormat('yyyy-MM-dd').format(DateTime.now()),
                        readOnly: true,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Price',
                        ),
                        initialValue: product.price.toString(),
                        validator: (value) {
                          if (value!.isEmpty) {
                            return "The Price Can't be Empty";
                          } else if (int.parse(value) < 0) {
                            return "The Price Should Large Than 0";
                          }
                          return null;
                        },
                        onSaved: (newValue) => newProduct.price = newValue as int,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Image',
                        ),
                        initialValue: product.image,
                        onSaved: (newValue) => newProduct.image = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Manufacturer',
                        ),
                        initialValue: product.manufacturer,
                        onSaved: (newValue) => newProduct.manufacturer = newValue as String,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: ElevatedButton(
                        child: const Text("Submit"),
                        onPressed: () {
                          if (productFormKey.currentState!.validate()) {
                            productFormKey.currentState!.save();
                            onEditFinish(newProduct, type);
                            Navigator.pop(context);
                          }
                        },
                      ),
                    )
                  ],
                ),
              ),
            ],
          ),
        );
      }
    );
  }
}

